### ISSUE TITLE
Epic: Polishing for response to referee report

### ISSUE THREAD

**Issue by aimalz** [aimalz/qp#79]
I'm collecting things I really need to fix before a proper code release.

- [ ] ~~make it easy for users to add formats by making a parametrization class (like `scipy.stats.rv_continuous`, etc.), with consistent syntax for conversions to replace the `using` keyword, opens the door for implementing SparsePZ, FlexZBoost formats~~ punting this to a later code release
- [x] eliminate `qp.PDF.truth` in favor of using `mix_mod` and `qp.PDF.first`
- [ ] rename `histogram` parametrization to something like piecewise constant or `stepfunc` to reduce confusion and make the piecewise constant distribution consistent in interpolation, integration, etc.
- [ ] remove checking if parametrization exists/calculating with default parameters in favor of exceptions
- [ ] find a way around `infty` for converting quantiles to other parametrizations
- [ ] formalize interpolation options ~~and include option for user-defined callable~~ punting this to a later code release
- [ ] check for consistent style in documentation
- [ ] clean up excessive print statements
- [ ] ~~#88~~ punting this to a later code release
- [ ] #65 
- [x] move `qp.Ensemble.stack()` and other "derived" functions to `utils.py` instead of within the class and publish demos for the "derived" use cases
- [ ] ~~replace `qp.PDF.\[insert parametrization format here\]`with cleaner dict object~~ punting this to a later code release

**Comment by aimalz** [comment]
This has been partially addressed by #93.  Stay tuned for more soon!

**Comment by aimalz** [comment]
I'm closing this issue and moving over to #94 for future development with broader goals.
