### ISSUE TITLE
Epic: Major refactoring

### ISSUE THREAD

**Issue by aimalz** [aimalz/qp#94]
~~In the interest of time, I'm splitting #79.  What I can't do in time for an immediate code release to coincide with the paper, I will address in a future version.~~

The time for reach goals is now!  I'm migrating content from #79 now that the paper is all done.  Here's what I want to do next:

- [ ] make it easy for users to add formats by making a parametrization class (like `scipy.stats.rv_continuous`, etc.), with consistent syntax for conversions to replace the `using` keyword, opens the door for implementing SparsePZ, FlexZBoost formats
- [ ] replace `qp.PDF.\[insert parametrization format here\]`with cleaner dict object
- [ ] remove checking if parametrization exists/calculating with default parameters in favor of exceptions
- [ ] #95
- [ ]  find a way around infty for converting quantiles to other parametrizations
- [ ] #35 
- [ ] rename histogram parametrization to stepfunc to reduce confusion
- [ ] make the piecewise constant distribution consistent in interpolation, integration, etc.
- [ ] formalize interpolation options
- [ ] #88
- [ ] check for consistent style in documentation
- [ ] clean up excessive print statements
